image: node:latest

stages:
  - check
  - test
  - sonar
  - build
  - deploy

cache:
  paths:
      - node_modules/


Security:
  stage: check
  script:
    - npx audit-ci --moderate

Lint:
  stage: check
  image: node:12
  script:
      - npm install
      - npm install --silent
      - npm run lint

Test:
  stage: test
  image: weboaks/node-karma-protractor-chrome
  script:
      - npm install --silent
      - npm run test

Sonar:
  stage: sonar
  script :
    - npm run sonar

Build:
  stage: build
  script:
     - npm run build
  artifacts:
    paths:
      - node_modules/

Production:
  image: node:8.11.3
  only:
    - master
  stage: deploy
  script:
    - npm run prod
  environment:
    name: production
    url: https://example.com

